name: 07 - Using expressions
run-name: 07 - Using Expressions | DEBUG - <${{inputs.debug == true && 'ON' || 'OFF'}}>

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] Print start-up data"
        if: ${{inputs.debug == true}}
        run: |
          echo "Triggered by: ${{github.event_name}}"
          echo "Branch: ${{github.ref_name}}"
      - name: "[debug] Print when triggered from main"
        if: ${{inputs.debug == true && github.ref_name == 'main'}}
        run: echo "I was triggered from main branch"
      - name: Greeting
        run: echo Hello world
  success:
    runs-on: ubuntu-latest
    steps:
      - name: Success step
        run: exit 1
  post-success:
    needs: success
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Post success step
        run: echo "I am a post success step"
