name: 08 - Using variables

on:
  workflow_dispatch:

env:
  W_VAR: "i am workflows env var"
  O_VAR: "I will be overwritten"
  UNDEFINED_VAR: ${{vars.UNDEFINED_VAR}}

jobs:
  echo:
    name: "My name is echo job"
    runs-on: ubuntu-latest
    env:
      J_VAR: "I am job env var"
      O_VAR: "I was overriden on job level"
    steps:
      - name: Print env vars
        env:
          STEP_VAR: "I am step env var"
          step_var2: "I am another step var"
        run: |
          echo "Step env var: ${{env.STEP_VAR}}"
          echo "Step env var 2: ${{env.step_var2}}"
          echo "Job env var: ${{env.J_VAR}}"
          echo "Workflow env var: ${{env.W_VAR}}"
          echo "Overriten: ${{env.O_VAR}}"
      - name: Overwrite job var
        env:
          O_VAR: "I was changed on step level"
        run: |
          echo "Step env var: ${{env.O_VAR}}"
  echo2:
    name: "I am echo two job"
    runs-on: ubuntu-latest
    steps:
      - name: Print vars
        run: |
          echo "Repo var: ${{vars.MY_REPO_VAR}}"
  echo-prod:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: Print prod vars
        run: |
          echo "Repo var ${{vars.MY_REPO_VAR}}"
          echo "Env var ${{vars.TARGET_VAR}}"
  echo-undefined:
    runs-on: ubuntu-latest
    steps:
      - name: Print undefined vars
        run: echo ${{vars.UNDEFINED_VAR}}
