name: 09 - Functions

on:
  workflow_dispatch:

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR title
        run: echo ${{github.event.pull_request.title}}
      - name: Print PR labels
        run: echo ${{toJson(github.event.pull_request.labels)}}
      - name: Bug step
        if: ${{ failure() && contains(github.event.pull_request.labels.*.name, 'fix') }}
        run: echo "I am a bug fix"

      - name: Sleep for 20 secs
        run: sleep 20
      - name: Failing step
        run: exit 1
      - name: I will be skipped
        if: ${{success()}}
        run: echo "I will print if prev job succeeds"
      - name: I will exec
        if: ${{failure()}}
        run: echo "I will print if any prev step fails"
      - name: I will exec
        if: ${{!cancelled()}}
        run: echo "I will print except when cancelled"
      - name: I will execute on canceled
        if: ${{cancelled()}}
        run: echo "Execution due to cancellation"
