name: 12 - Outputs

on:
  workflow_dispatch:
    inputs:
      build-status:
        type: choice
        options: [success, failure]
        default: success

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{steps.build.outputs.status}}
    steps:
      - name: Print GH output path
        run: echo $GITHUB_OUTPUT
      - name: Build
        id: build
        run: echo "status=${{inputs.build-status}}" >> $GITHUB_OUTPUT
      - name: Build job output
        run: cat $GITHUB_OUTPUT
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{needs.build.outputs.build-status == 'success'}}
    steps:
      - name: Deploy
        run: echo "Deploying because status is ${{needs.build.outputs.build-status}}"
      - name: Step level output generator
        id: output-generator
        run: |
          echo "name=Hello" >> $GITHUB_OUTPUT
          echo "lastname=World" >> $GITHUB_OUTPUT
      - name: Step level output consumer
        run: |
          echo "Step output name is ${{steps.output-generator.outputs.name}}"
          echo "Step output lastname is ${{steps.output-generator.outputs.lastname}}"
      - name: Step level Print output
        run: |
         cat $GITHUB_OUTPUT