name: 13 - Caching

on:
  workflow_dispatch:
    inputs:
      use-cache:
        type: boolean
        default: true
        description: Do you want to execute cache step?

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react-app
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Download cached deps
        id: cache
        if: ${{inputs.use-cache == true}}
        uses: actions/cache@v5
        with:
          key: deps-node-modules-${{hashFiles('react-app/pnpm-lock.yaml')}}
          path: react-app/node-modules
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'
          cache-dependency-path: 'react-app/pnpm-lock.yaml'
      - name: Install dependencies
        if: ${{steps.cache.outputs.cache-hit != 'true'}}
        run: pnpm install --frozen-lockfile
      # - name: Install deps
      #   run: pnpm install --frozen-lockfile
      - run: pnpm test
      - run: pnpm build
      - run: echo "Deploying to nonprod"
          


