name: 17.2 - Custom actions (JS)

on:
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo title
        uses: ./.github/actions/title-logger
        with:
          title: ${{github.event.pull_request.title}}
