name: 17.2 - Custom actions (JS)

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  echo:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      # - name: Add ticket link
      #   uses: ./.github/actions/ticket-link
      #   with:
      #     title: ${{github.event.pull_request.title}}
      #     github-token: ${{secrets.GITHUB_TOKEN}}

      - name: Add ticket link (Docker)
        uses: ./.github/actions/docker-ticket-link
        with:
          title: ${{github.event.pull_request.title}}
          github-token: ${{secrets.GITHUB_TOKEN}}
