name: 17.2 - Custom actions (JS)

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  echo:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Add ticket link
        id: ticket-link
        uses: ./.github/actions/ticket-link
        with:
          title: ${{github.event.pull_request.title}}
          github-token: ${{secrets.GITHUB_TOKEN}}
      - name: Echo ticket link
        run: echo "Ticket link ${{steps.ticket-link.outputs.ticket-link}}"
      - name: Echo ticket number
        run: echo "Ticket number ${{steps.ticket-link.outputs.ticket-number}}"

      # - name: Add ticket link (Docker)
      #   uses: ./.github/actions/docker-ticket-link
      #   with:
      #     title: ${{github.event.pull_request.title}}
      #     github-token: ${{secrets.GITHUB_TOKEN}}
