name: 17 - Consuming reusable action
run-name: Consuming action | env - ${{inputs.target-env}}

on:
  workflow_dispatch:
    inputs:
      target-env:
        type: choice
        options:
          - dev
          - prod

env:
  working-directory: ./react-app

jobs:
  build:
    outputs:
      install-is-success: ${{steps.dependency-setup.outputs.installation_success}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup pnpm and nodejs
        id: dependency-setup
        uses: ./.github/actions/pnpm-node-setup
        with:
          node-version: 24
          work-dir: ${{env.working-directory}}
          pnpm-version: 10
      - name: Build project
        working-directory: ${{env.working-directory}}
        run: |
          echo ${{steps.dependency-setup.outputs.installation_success}}
          pnpm build
  result:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{needs.build.outputs.install-is-success}}
