name: 17 - Consuming reusable action

on:
  workflow_dispatch:

jobs:
  build:
    outputs:
      install-is-success: ${{steps.dependency-setup.outputs.installation_success}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup pnpm and nodejs
        id: dependency-setup
        uses: ./.github/actions/pnpm-node-setup
        with:
          node-version: 24
          work-dir: ./react-app
          pnpm-version: 10
      - name: Build project
        run: |
          echo ${{steps.dependency-setup.outputs.install-is-success}}
          pnpm build
