name: 18.1 - Reusable workflows

on:
  workflow_call:
    inputs:
      target-directory:
        type: string
        required: true
    outputs:
      build-status:
        description: Build process status
        value: ${{jobs.deploy.outputs.build-status}}
      url:
        description: The url of the deployed version
        value: ${{jobs.deploy.outputs}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{steps.build.outputs.build-status}}
      url: ${{steps.deploy.outputs.url}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Build
        id: build
        run: |
          echo "Building using directory ${{inputs.target-directory}}"
          echo "build-status=success" >> "$GITHUB_OUTPUT"
      - name: Deploy
        id: deploy
        run: |
          echo "Deploying build artifacts"
          echo "url=https://www.google.com" >> "$GITHUB_OUTPUT"
